config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
        sessions: 'admin/sessions'
      }

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  root to: "homes#top"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :notifications,only: [:index, :create] #onlyでだけ
  #get 'notifications/index'
  #get 'notifications/create'

  resources :likes,only: [:create, :destroy]
  #get 'likes/create'
  #get 'likes/destroy'

  resources :comments,only: [:create, :destroy]
  #get 'comments/create'
  #get 'comments/destroy'

  namespace :admin do
    resources :users,except: [:new, :create, :destroy] do#except除外する書き方
      get 'unsubscribe'
      patch 'withdrawal'
    end
    #get 'users/index'
    #get 'users/show'
    #get 'users/edit'
    #get 'users/update'
  end

  namespace :admin do
    get 'homes/top'
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  resources :users,only: [:show, :edit, :update, :index] do
    get 'unsubscribe'
    patch 'withdrawal'
    member do
      get :likes
    end
  end
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'

  resources :posts do  #7つ含まれている　[index,show,new,create,edit,update,destroy]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/destroy'

  get 'homes/top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image#画像を保存させる機能

  #↓住所登録時と変更時にgeocoderが緯度・経度のデータを登録・更新してくれる
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  has_many :comments, dependent: :destroy #dependent: :destroyこの場合　投稿が削除されると今までのコメントが自動的に削除される
  has_many :likes
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy



  def liked_by?(user) #いいね機能色判定
    likes.exists?(user_id: user.id)
  end

  #enum prefecture_id: { #新規投稿の都道府県のタグ選択
    #北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    #茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    #新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    #岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    #滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    #鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    #徳島県:36,香川県:37,愛媛県:38,高知県:39,
    #福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  #}

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_users_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index] #exceptが除く

  def index
    if params[:tag_ids]
      tags = params[:tag_ids].select {|k, v| v == "1" }.keys
      @posts = Kaminari.paginate_array(Tag.where(name: tags).map {|tag| tag.posts}.flatten).page(params[:page]).per(3)
    else
      @posts = Post.all.page(params[:page]).per(3)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = User.find(@post.user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save! #！マークをつけるとセーブされているかの確認
    redirect_to post_path(@post.id)
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('explanation LIKE ?', "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :explanation, :prefecture_id, :user_id, :address, :latitude, :longitude, tag_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="container">
    <%= link_to post_path(post.id), style: "color: black;" do %>
        <%= post.user.name  %>・<%= post.title %>
        <i class="fa fa-heart unlike-btn"></i>
    <% end %>
    <%#= いいねされた投稿　投稿タイトル名・いいねをした人の名前を表示投稿詳細ページに飛ぶ　※ユーザー紹介ページに飛ぶ%>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="posts.css">

    <div class="back">
        <div class="row justify-content-md-center">
            <h1>投稿一覧</h1>
        </div>
        <div class="container">
            <%= form_with url: search_posts_path, local: true, method: :get do |form| %><%#=キーワード検索%>
                <%= form.text_field :keyword %>
                <%= form.submit "検索" %>
            <% end %>

            <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>タグ検索
                <% Tag.all.each do |t| %>
                    <span class="pb-2"><%= check_box :tag_ids, t.name %><%= t.name %><%#= form.check_box :tag_ids, t.name { multiple: true, include_hidden: false }, tag_ids %></span>
                <% end %>
                <%= submit_tag '検索' %>
            <% end %>

            <div class="col"></div>

            <div class="row justify-content-md-center">
                <div class="topnewbox">
                    <% @posts.each do |post| %>
                        <div class="card" style="width: 18rem;">
                            <%= link_to post_path(post.id), style: "color: black;" do %>
                                <%= image_tag post.image, size: "250x150" %>
                                <div class="card-body">
                                    <p class="card-text">
                                        タイトル名・<%= post.title %></br>
                                        投稿者名・<%= post.user.name %></br>
                                        <% post.tags.each do |tag| %>
                                            地名タグ・<span><label for="tag_ids_<%= tag.name %>"><%= tag.name %></label></span></br>
                                        <% end %>
                                        いいね数・<%= post.likes.count %>
                                    </p>
                                </div>
                            <% end %>
                        </div>
                    <% end %>

                </div>

            </div>

            <div class="col"></div>

            <div class="row justify-content-md-center">
                <div class="paginate">
                    <%= paginate @posts %> <%#=ページネーション記述%>
                </div>
            </div>
        </div>
    </div>

</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<meta charset="UTF-8" />
<link rel="stylesheet" href="posts.css">

<div class="box6">
    <div class="row justify-content-md-center">
      <h1>新規投稿</h1>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <%= form_with model: @post, url: posts_path do |f| %>
                <div class="field">
                    <%= f.label "タイトル名" %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="col"></div>
                <div class="field">
                    <%= f.label "写真・画像を選択" %>
                    <%= f.file_field :image, accept: "image/*", class: "form-control" %>
                </div>
                <div class="col"></div>
                <div class="field">
                    <%= f.label "説明を入力" %>
                    <%= f.text_area :explanation, rows: "10", class: "form-control" %>
                </div>
                <div class="col"></div>
                <div class="field">
                    <%= f.label :地図情報入力, class: "form-label fw-bold"%>
                    <%= f.text_field :address, autofocus: true,placeholder: "住所を入力してください", class: "form-control" %><%#= f.submit (@post.new_record? ? "投稿する" : "更新する"), class: "btn btn-primary mb-4" %>
                </div>
                <div class="col"></div>
                <div class="field">
                    <%= f.label "地名タグを選択", class: 'd-block' %>
                    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                        <div class="form-check d-inline">
                            <%= tag.label class: 'form-check-label' do %><%#= f.select :prefecture_id, Post.prefecture_ids.keys, {prompt: '選択してください'} %> <%#配列を入れる※複数形で記述 　今回はモデルでenumを定義しているカラム名を入れる　%>
                                <%= tag.check_box class: 'form-check-input' %>
                                <%= tag.text %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
                <div class="col"></div>
                <div class="actions">
                    <%= f.submit '投稿', class: "btn btn-lg btn-primary btn-block" %>
                </div>
                <div class="col"></div>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/search.html.erb
<div class="back">
  <div class="row justify-content-md-center">
    <h1>検索結果 "<%= @keyword %>"</h1>
  </div>

  <div class="container">
    <%= form_with url: search_posts_path, local: true, method: :get do |form| %><%#=キーワード検索%>
      <%= form.text_field :keyword %>
      <%= form.submit "検索" %>
    <% end %>

    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>タグ検索
      <% Tag.all.each do |t| %>
        <span class="pb-2"><%= check_box :tag_ids, t.name %><%= t.name %></span>
      <% end %>
      <%= submit_tag '検索' %>
    <% end %>

    <div class="col"></div>

    <div class="row justify-content-md-center">
      <div class="topnewbox">
        <% @posts.each do |post| %>
          <div class="card" style="width: 18rem;">
            <%= link_to post_path(post.id), style: "color: black;" do %>
              <%= image_tag post.image, size: "250x150" %>
              <div class="card-body">
                <p class="card-text">
                  タイトル名・<%= post.title %></br>
                  投稿者名・<%= post.user.name %></br>
                  <% post.tags.each do |tag| %>
                    地名タグ・<span><label for="tag_ids_<%= tag.name %>"><%= tag.name %></label></span></br>
                  <% end %>
                  いいね数・<%= post.likes.count %>
                </p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="paginate">
        <%#= paginate @posts %>
      </div>
    </div>

  </div>
</div>

app/views/posts/show.html.erb
<div class="box7">
  <div class="row justify-content-md-center">
    <h1>投稿詳細</h1>
  </div>

  <div class="row justify-content-md-center">
    <div class="container">
      <div class="card" style="width: 15rem;"><%#= 投稿ユーザー情報%>
        <%= link_to user_path(@post.user_id), style: "color: black;" do %><%#= 画像・名前・年齢・性別%><%#= image_tag @post.user.image, size: "200x200" %>
          <div class="card-body">
            <h5 class="card-title">投稿者情報 <i class="fa-solid fa-user"></i></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= @post.user.name %></h6>
            <p class="card-subtitle mb-2 text-muted"><%= @post.user.age %>歳<%= @post.user.gender %></p>
          </div>
        <% end %>
      </div>
      <div class="col"></div>
      <div class="box8">
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="card" style="width: 70rem;"><%#= 投稿情報%>
              <div class="image">
                <% if @post.image.attached? %>
                  <%= image_tag @post.image, size: "300x300" %> <%#= 写真表示%>
                <% end %>
              </div>
              <div class="card-body">
              <p class="card-text">
                タイトル名・<%= @post.title %></br> <%#= タイトル名%>
                説明・<%= @post.explanation %></br> <%#= 説明%>
                <% @post.tags.each do |tag| %><%#= 地名タグ%>
                  地名タグ・<span><%= tag.name %></span>
                <% end %>
                <%#= いいね機能%>
                <% if @post.liked_by?(current_user) %>
                  <p>
                    いいね数 <%= @post.likes.count %>
                    <%= link_to post_likes_path(@post), method: :delete do %>
                       <i class="fas fa-heart unlike-btn"><%= @post.likes.count %></i>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    いいね数 <%= @post.likes.count %>
                    <%= link_to post_likes_path(@post), method: :post do %>
                      <i class="far fa-heart like-btn">いいね！<%= @post.likes.count %></i>
                    <% end %>
                  </p>
                <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col"></div>
      <% if current_user == @user %> <%#= 投稿したユーザーにのみ表示%>
        <button type="button" class="btn btn-danger"><%= link_to "投稿削除", post_path(@post), method: :delete, style: "color: black;" %></button>
      <% end %>
    </div>
  </div>

  <div class="col"></div>

  <div class="container">
    <div class="row justify-content-md-center">
      <h5>~エリア情報~</h5></br>
      <p><%= @post.address %></p>
      <div id="map"><!-- Googleマップ表示エリア(地図を表示) --></div>
    </div>
  </div>

  <div class="col"></div>

  <div class="container">
    <div class="">
      <%#= コメント機能 %>
      <p><i class="fa-regular fa-comment"></i>コメント件数：<%= @post.comments.count %></p>
      <% @post.comments.each do |comment| %>
       <div>
        <%= link_to user_path(comment.user_id), style: "color: black;" do %>
          <%= comment.user.name %></br>
        <% end %>
        <i class="fa-regular fa-comment"></i>
        <%= comment.body %>
        <%= comment.created_at.strftime('%Y/%m/%d') %>
        <% if comment.user == current_user %>
          <button><%= link_to "削除", post_comment_path(comment.id), method: :delete %></button>
        <% end %>
       </div>
      <% end %>

      <div class="col"></div>

      <%= form_with model: [@post, @comment] do |f| %>
        <%= f.text_area :body, rows: '10', placeholder: "コメントをここに", class: "form-control" %>
        <div class="col"></div>
        <div class="actions">
          <%= f.submit "送信する", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
      <div class="col"></div>
    </div>
  </div>

</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script><%#= <%= ENV['GOOGLE_MAP_API_KEY'] %>

<!-- Googleマップ表示用の Javascript -->
<script>
  function initMap(){
    // 地図の位置情報(緯度・経度)を取得
    let mapPosition = {lat: <%= @post.latitude || 0 %> , lng: <%= @post.longitude || 0 %> };
    let map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: mapPosition
    });
//    let transitLayer = new google.maps.TransitLayer();
//    transitLayer.setMap(map);

    let contentString = '【住所】<%= @post.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    let marker = new google.maps.Marker({
      position: mapPosition,
      map: map,
      title: contentString
    });

    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });
  }
</script>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>