config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
        sessions: 'admin/sessions'
      }

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  root to: "homes#top"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :notifications,only: [:index, :create] #onlyでだけ
  #get 'notifications/index'
  #get 'notifications/create'

  resources :likes,only: [:create, :destroy]
  #get 'likes/create'
  #get 'likes/destroy'

  resources :comments,only: [:create, :destroy]
  #get 'comments/create'
  #get 'comments/destroy'

  namespace :admin do
    resources :users,except: [:new, :create, :destroy] do#except除外する書き方
      get 'unsubscribe'
      patch 'withdrawal'
    end
    #get 'users/index'
    #get 'users/show'
    #get 'users/edit'
    #get 'users/update'
  end

  namespace :admin do
    get 'homes/top'
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  resources :users,only: [:show, :edit, :update, :index] do
    get 'unsubscribe'
    patch 'withdrawal'
    member do
      get :likes
    end
  end
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'

  resources :posts do  #7つ含まれている　[index,show,new,create,edit,update,destroy]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/destroy'

  get 'homes/top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image

  has_many :posts
  has_many :likes, dependent: :destroy #いいね
  has_many :comments, dependent: :destroy #dependent: :destroyこの場合　ユーザーが退会すると退会したユーザーのコメントが自動的に削除される

  def self.guest #ゲストログインの情報
    user=find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
      user.age = "22歳"
      user.gender = "男性"
      user.introduction ="自己紹介ですよ"
      user.telephone_number ="０９０１２３４５６７８"
    end
    file_path = Rails.root.join('app/assets/images/bicycle.jpg')
    user.image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    user
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def withdrawal
    @user = User.find(params[:user_id])
    if @user.update(is_active: false)
      #reset_session 今ログインしている人がログアウト
      redirect_to admin_users_path
    else
      render :unsubscribe
    end
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:email, :image, :name, :age, :gender, :introduction, :telephone_number, :is_active )
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user.id), notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:likes]

  def likes
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def edit
    @users = current_user #複数系でログインしているユーザー
  end

  def update
    @users = current_user
    if @users.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def unsubscribe

  end

  def withdrawal
    @users = current_user
    if @users.update(is_active: false)
      reset_session
      redirect_to homes_top_path
    else
      render :unsubscribe
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :gender, :introduction, :image, :email, :telephone_number, :encrypted_password, :is_active)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class="row justify-content-md-center">
  <h1>会員一覧</h1>
</div>

<div class="container">
  <div class="row justify-content-md-center">

    <table class="table table-hover table-inverse",border="1">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>Email</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to admin_user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_active == false %>
                退会
              <% else %>
                有効
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row justify-content-md-center">
  <h1>会員情報</h1>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="card">
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag @user.image, class: "rounded-circle", size: "200x200" %>
          </div>
          <div class="col-md-9">
            <div class="card-body">
              <h5 class="card-title">名前・<%= @user.name %></h5>
              <p class="card-text">
                年齢・<%= @user.age %>
                性別・<%= @user.gender %>
              </p>
              <p class="card-text"></br><%= @user.introduction %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col"></div>

  <div class="row justify-content-md-center">

    <table class="table table-hover table-inverse",border="1">
      <thead>
        <tr>
          <th>投稿タイトル一覧</th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, admin_post_path(post.id) %> <%#タイトルと詳細画面のパス%></td>
        </tr>
        <% end %>
      </tbody>

    </table>

    <div class="col"></div>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class="row">
          <%= link_to admin_user_unsubscribe_path(@user.id) do %>
            <button type="button" class="btn btn-warning">退会</button>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col"></div>

  </div>

</div>

app/views/admin/users/unsubscribe.html.erb
  <div class="row justify-content-md-center">
    <h1>退会</h1>
  </div>
<div class="col"></div>
<div class="col"></div>
<div class="col"></div>

  <div class="container">
    <div class="row justify-content-md-center">
      <p>
        <div class="box13">
          退会すると、
          これまでの投稿情報が閲覧できなくなります。</br>
          退会する場合は、「退会させる」をクリックしてください。
        </div>
      </p>
    </div>
  </div>

  <div class="col"></div>
  <div class="col"></div>
  <div class="col"></div>
  <div class="col"></div>
  <div class="col"></div>
  <div class="col"></div>

  <div class="container">
    <div class="row justify-content-md-center">
      <%= link_to admin_user_withdrawal_path, method: :patch, "data-confirm" => "本当に退会させますか？" do %>
        <button type="button" class="btn btn-danger">
          退会させる
        </button>
      <% end %>
    </div>
  </div>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>