config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
        sessions: 'admin/sessions'
      }

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  root to: "homes#top"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :notifications,only: [:index, :create] #onlyでだけ
  #get 'notifications/index'
  #get 'notifications/create'

  resources :likes,only: [:create, :destroy]
  #get 'likes/create'
  #get 'likes/destroy'

  resources :comments,only: [:create, :destroy]
  #get 'comments/create'
  #get 'comments/destroy'

  namespace :admin do
    resources :users,except: [:new, :create, :destroy] do#except除外する書き方
      get 'unsubscribe'
      patch 'withdrawal'
    end
    #get 'users/index'
    #get 'users/show'
    #get 'users/edit'
    #get 'users/update'
  end

  namespace :admin do
    get 'homes/top'
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  resources :users,only: [:show, :edit, :update, :index] do
    get 'unsubscribe'
    patch 'withdrawal'
    member do
      get :likes
    end
  end
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'

  resources :posts do  #7つ含まれている　[index,show,new,create,edit,update,destroy]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/destroy'

  get 'homes/top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image#画像を保存させる機能

  #↓住所登録時と変更時にgeocoderが緯度・経度のデータを登録・更新してくれる
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  has_many :comments, dependent: :destroy #dependent: :destroyこの場合　投稿が削除されると今までのコメントが自動的に削除される
  has_many :likes
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy



  def liked_by?(user) #いいね機能色判定
    likes.exists?(user_id: user.id)
  end

  #enum prefecture_id: { #新規投稿の都道府県のタグ選択
    #北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    #茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    #新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    #岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    #滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    #鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    #徳島県:36,香川県:37,愛媛県:38,高知県:39,
    #福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  #}

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image

  has_many :posts
  has_many :likes, dependent: :destroy #いいね
  has_many :comments, dependent: :destroy #dependent: :destroyこの場合　ユーザーが退会すると退会したユーザーのコメントが自動的に削除される

  def self.guest #ゲストログインの情報
    user=find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
      user.age = "22歳"
      user.gender = "男性"
      user.introduction ="自己紹介ですよ"
      user.telephone_number ="０９０１２３４５６７８"
    end
    file_path = Rails.root.join('app/assets/images/bicycle.jpg')
    user.image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    user
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: post.id)
    like.save
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to post_path(post.id)
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index] #exceptが除く

  def index
    if params[:tag_ids]
      tags = params[:tag_ids].select {|k, v| v == "1" }.keys
      @posts = Kaminari.paginate_array(Tag.where(name: tags).map {|tag| tag.posts}.flatten).page(params[:page]).per(3)
    else
      @posts = Post.all.page(params[:page]).per(3)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = User.find(@post.user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save! #！マークをつけるとセーブされているかの確認
    redirect_to post_path(@post.id)
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('explanation LIKE ?', "%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :explanation, :prefecture_id, :user_id, :address, :latitude, :longitude, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:likes]

  def likes
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def edit
    @users = current_user #複数系でログインしているユーザー
  end

  def update
    @users = current_user
    if @users.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def unsubscribe

  end

  def withdrawal
    @users = current_user
    if @users.update(is_active: false)
      reset_session
      redirect_to homes_top_path
    else
      render :unsubscribe
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :gender, :introduction, :image, :email, :telephone_number, :encrypted_password, :is_active)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
      <title>Bicycle Adventure</title>

    <!--<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <% if user_signed_in? %> <%#ログインしているときの場合%>

        <div class="row justify-content-md-center">
          <div class="title1">
            <%= link_to "~Bicycle Adventure~", homes_top_path, style: "color: black;", class:"top"%>
          </div>
        </div>

        <div class="container">
          <div class="row row-cols-4">
            <div class="col">
              <%= link_to new_post_path do %>
                <button type="button" class="btn btn-light">
                  新規投稿
                </button>
              <% end %>
            </div>
            <div class="col">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <button type="button" class="btn btn-light">
                  ログアウト
                </button>
              <% end %>
            </div>
            <div class="col">
              <%= link_to posts_path do %>
                <button type="button" class="btn btn-light">
                  投稿一覧
                </button>
              <% end %>
            </div>
            <div class="col">

              <%= link_to user_path(current_user.id) do %>
                <button type="button" class="btn btn-light">
                  マイページ
                </button>
              <% end %>
            </div>
          </div>
        </div>

      <% elsif admin_signed_in? %>
        <div class="row justify-content-md-center">
          <div class="title1">
            <%= "~Bicycle Adventure~" %>
          </div>
        </div>

        <div class="container">
          <div class="row row-cols-4">
            <div class="col"></div>
            <div class="col">

              <%= link_to admin_users_path do %>
                <button type="button" class="btn btn-light">
                  会員一覧
                </button>
              <% end %>
            </div>
            <div class="col">
              <%= link_to destroy_admin_session_path, method: :delete do %>
                <button type="button" class="btn btn-light">
                  管理者ログアウト
                </button>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>

        <div class="title1">
          <%= link_to "~Bicycle Adventure~", homes_top_path, style: "color: black;", class:"top"%>
        </div>


        <div class="container">
          <div class="row">
          <div class="col-sm-9"></div>
          <div class="col-sm-3">
            <%= link_to new_admin_session_path do %>
              <button type="button" class="btn btn-dark">
                管理者ログイン
              </button>
            <% end %>
          </div>
          </div>
        </div>

        <div class="container">
          <div class="row row-cols-4">
            <div class="col">
              <%= link_to new_user_registration_path do %>
                <button type="button" class="btn btn-light">
                  新規登録
                </button>
              <% end %>
            </div>
            <div class="col">
              <%= link_to new_user_session_path do %>
                <button type="button" class="btn btn-light">
                  ログイン
                </button>
              <% end %>
            </div>
            <div class="col">
              <%= link_to posts_path do %>
                <button type="button" class="btn btn-light">
                  投稿一覧
                </button>
              <% end %>
            </div>
            <div class="col">

              <%= link_to users_guest_sign_in_path, method: :post do %>
                <button type="button" class="btn btn-dark">
                  ゲストログイン（閲覧用）
                </button>
              <% end %>
            </div>
          </div>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>